"""Configure and setup a program executionOptional\[ of the GalWrap package.
"""

# Imports


from pathlib import Path
import logging

import yaml
from astropy.table import Table

from . import paths

from .objects import FICLO, GalWrapConfig, GALWRAP_PATHS
from ..utils import science


# Logger


logger = logging.getLogger("CONFIG")
"""Logger object for this module.
"""


# Functions


def create_config(
    config_path: str | Path | None = None,
    input_root: str | Path | None = None,
    product_root: str | Path | None = None,
    output_root: str | Path | None = None,
    field: str | None = None,
    fields: list[str] | None = None,
    image_version: str | None = None,
    image_versions: list[str] | None = None,
    catalog_version: str | None = None,
    catalog_versions: list[str] | None = None,
    filter: str | None = None,
    filters: list[str] | None = None,
    object: int | None = None,
    objects: list[int] | None = None,
    pixscale: float | None = None,
    pixscales: list[float] | None = None,
    morphology_version: str | None = None,
    morphology_versions: list[str] | None = None,
) -> GalWrapConfig:
    """Create a configuration object from hierarchically preferred variables, in
    order of CLI passed values, then config file declared values, then values
    found by directory discovery.

    Parameters
    ----------
    config_path : str | Path | None, optional
        Path to user config yaml file, by default None (no user config file
        provided).
    input_root : str | Path | None, optional
        Path to root directory of input products, e.g. catalogs, science images,
        and PSFs, by default None (not passed through CLI).
    product_root : str | Path | None, optional
        Path to root directory of products generated by this program to execute
        GALFIT, e.g. cutouts/stamps, masks, and feedfiles, by default None (not
        passed through CLI).
    output_root : str | Path | None, optional
        Path to root directory of GALFIT output products, e.g. morphology model
        and plots, by default None (not passed through CLI).
    field : str | None, optional
        Single field over which to execute GALFIT, by default None (not passed
        through CLI).
    fields : list[str] | None, optional
        List of fields over which to execute GALFIT, by default None (not passed
        through CLI).
    image_version : str | None, optional
        Single image version over which to execute GALFIT, by default None (not
        passed through CLI).
    image_versions : list[str] | None, optional
        List of image versions over which to execute GALFIT, by default None
        (not passed through CLI).
    catalog_version : str | None, optional
        Single catalog version over which to execute GALFIT, by default None
        (not passed through CLI).
    catalog_versions : list[str] | None, optional
        List of catalog versions over which to execute GALFIT, by default None
        (not passed through CLI).
    filter : str | None, optional
        Single filter band over which to execute GALFIT, by default None (not
        passed through CLI).
    filters : list[str] | None, optional
        List of filter bands over which to execute GALFIT, by default None (not
        passed through CLI).
    object : int | None, optional
        Single target IDs over which to execute GALFIT, for each catalog, by
        default None (not passed through CLI).
    objects : list[int] | None, optional
        List of target IDs over which to execute GALFIT, for each catalog, by
        default None (not passed through CLI).
    pixscale : float | None, optional
        Single pixel scale over which to execute GALFIT, by default None (not
        passed through CLI).
    pixscales : list[float] | None, optional
        List of pixel scales over which to execute GALFIT, by default None (not
        passed through CLI).
    morphology_version : str | None, optional
        Single morphology fitting method to execute, by default None (not passed
        through CLI).
    morphology_versions : list[str] | None, optional
        List of morphology fitting methods to execute, by default None (not
        passed through CLI).

    Returns
    -------
    GalWrapConfig
        A configuration object for this program execution.

    Notes
    -----
    If both the single and multiple version for a variable are given (e.g.
    `field` and `fields` both have values from CLI), only the single version
    will be used.
    """
    # Load config file values
    config_dict = {} if config_path is None else yaml.safe_load(open(config_path))
    ## Cast and resolve paths
    for config_key in ["input_root", "product_root", "output_root"]:
        if config_key in config_dict:
            config_dict[config_key] = Path(config_dict[config_key]).resolve()

    # Set any parameters passed through CLI call
    ## Paths
    if input_root is not None:
        config_dict["input_root"] = paths.get_path_obj(input_root)
    if product_root is not None:
        config_dict["product_root"] = paths.get_path_obj(product_root)
    if output_root is not None:
        config_dict["output_root"] = paths.get_path_obj(output_root)

    ## Multiple FICLOs
    if fields is not None:
        config_dict["fields"] = fields
    if image_versions is not None:
        config_dict["image_versions"] = image_versions
    if catalog_versions is not None:
        config_dict["catalog_versions"] = catalog_versions
    if filters is not None:
        config_dict["filters"] = filters
    if objects is not None:
        config_dict["objects"] = objects
    if pixscales is not None:
        config_dict["pixscales"] = pixscales
    if morphology_versions is not None:
        config_dict["morphology_versions"] = morphology_versions

    ## Single FICLOs - note this will override multiple FICLOs if set
    if field is not None:
        config_dict["fields"] = [field]
    if image_version is not None:
        config_dict["image_versions"] = [image_version]
    if catalog_version is not None:
        config_dict["catalog_versions"] = [catalog_version]
    if filter is not None:
        config_dict["filters"] = [filter]
    if object is not None:
        config_dict["objects"] = [object]
    if pixscale is not None:
        config_dict["pixscales"] = [pixscale]
    if morphology_version is not None:
        config_dict["morphology_versions"] = [morphology_version]

    # TODO If parameters are still unset, assume program execution over all
    # discovered values in input directory

    # Path
    ## Terminate if input root not found
    if "input_root" not in config_dict:
        raise FileNotFoundError(f"Input root not passed, terminating.")
    ## Create other roots if not found
    for config_key in ["product_root", "output_root"]:
        if config_key not in config_dict:
            input_root_typing: Path = config_dict["input_root"]
            root = input_root_typing.parent
            config_dict[config_key] = GALWRAP_PATHS[config_key].resolve(root=root)

    # FICLOs
    if "fields" not in config_dict:
        config_dict["fields"] = paths.find_parameters(
            "field", input_root=config_dict["input_root"]
        )
    if "image_versions" not in config_dict:
        config_dict["image_versions"] = paths.find_parameters(
            "image_version", input_root=config_dict["input_root"]
        )
    if "catalog_versions" not in config_dict:
        config_dict["catalog_versions"] = paths.find_parameters(
            "catalog_version", input_root=config_dict["input_root"]
        )
    if "filters" not in config_dict:
        config_dict["filters"] = paths.find_parameters(
            "filter", input_root=config_dict["input_root"]
        )
    if "objects" not in config_dict:
        config_dict["objects"] = paths.find_parameters(
            "object", input_root=config_dict["input_root"]
        )

    # Create GalWrapConfig from dict
    galwrap_config = GalWrapConfig(**config_dict)

    # # Setup directories
    # path.setup_directories(galwrap_config=galwrap_config)

    # # Create filter info tables
    # ## TODO set how ofic is chosen
    # input_science_files: list[Path] = path.get_path(
    #     "file_science_images", galwrap_config=galwrap_config, ofic=ofic
    # )
    # for input_science_file in input_science_files:
    #     galwrap_config.filters.append(
    #         input_science_file.name.split("-")[1].split("_")[0]
    #     )
    # ## TODO is this where pixscales are from?
    # galwrap_config.pixscales.append("40mas")

    # ## Create table of three columns in order of filters, pixscales, and pixnames
    # num_filters = len(galwrap_config.filters)
    # filter_info = Table(
    #     [
    #         galwrap_config.filters,
    #         [galwrap_config.pixscales[0] for i in range(num_filters)],
    #         [
    #             utils.scale_to_name(galwrap_config.pixscales[0])
    #             for i in range(num_filters)
    #         ],
    #     ]
    # )

    # ## Write table to file
    # ascii.write(
    #     filter_info,
    #     path.get_path("file_filter_info", galwrap_config=galwrap_config, ofic=ofic),
    # )

    # Return created config object
    return galwrap_config


# Instantiations


galwrap_config = create_config()
"""Config object instantiation.
"""
