galfit_path: path/to/galfit
input_root: ./examples/single_ficlo/morphfits_root/input/
fields:
  - "smacs0723"
image_versions:
  - "grizli-v7.0"
catalog_versions:
  - "dja-v7.2"
filters:
  - "f200w-clear"
objects:
  - 10000
wrappers:
  - "galfit"
