input_root: ./examples/single_ficlo/data/input/
fields:
  - "abell2744clu"
image_versions:
  - "grizli-v7.2"
catalog_versions:
  - "dja-v7.2"
filters:
  - "f200w-clear"
objects:
  - 4215
wrappers:
  - "galfit"
