galfit_path: path/to/galfit
input_root: ./examples/uncover_run/morphfits_root/input/
fields:
  - "abell2744clu"
image_versions:
  - "grizli-v7.2"
catalog_versions:
  - "dja-v7.2"
filters:
  - f150w-clear
first_object: 4200
last_object: 4300
